apollo_profile: github
spring:
  application:
    name: config-service
  profiles:
    active: ${apollo_profile}
#  datasource:
#    url: jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8
#    username: root
#    password: 123456  
ctrip:
  appid: 100003171
server:
  port: 8888
logging:
  file: /opt/log/100003171/config-service.log
